#!/bin/sh
#
# SCRIPT: rpc
# AUTHOR: nickeywoo <thenickey@gmail.com>
# DATE: 2014/7/27
#

BASEPATH=`dirname $0`

usage() {
	echo "Usage: rpc [build|dump|help]"
}

build() {
	if [ $# -lt 3 ]
	then
		echo "Usage: rpc build [proto file] [template path]"
		exit 1;
	fi
	if !([ -f $2 ])
	then
		echo "error: not found proto file."
		exit 2;
	fi
	if !([ -d $3 ])
	then
		echo "error: not found templates."
		exit 2;
	fi
	OTHER=`other 3 "$*"`
	export PROTOCGENRPC_TEMPLATE=$3
	protoc --plugin=$BASEPATH/protoc-gen-rpc --rpc_out=./ $2 $OTHER
}

dump() {
	if [ $# -lt 2 ]
	then
		echo "Usage: rpc dump [proto file]"
		exit 1;
	fi
	if !([ -f $2 ])
	then
		echo "error: not found proto file."
		exit 2;
	fi
	OTHER=`other 2 "$*"`
	export PROTOCGENRPC_TEMPLATE=""
	protoc --plugin=$BASEPATH/protoc-gen-rpc --rpc_out=./ $2 $OTHER
}

other() {
	RET=""
	i=1
	for X in $2
	do
		if [ $i -gt $1 ]
		then
			RET="$RET $X"
		fi
		i=$(($i+1))
	done
	echo $RET
}

case "$1" in
	build)
		build $@
		;;
	dump)
		dump $@
		;;
	help)
		usage $@
		;;
	*)
		usage $@
esac





